[package]
name = "hardqoi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "^1.10.0"
image = {version = "^0.24.2", optional = true }

[features]
default = ["image_compat"]
use_std = []
use_simd = []
image_compat = ["dep:image"]

[[bin]]
name = "hardqoi"
path = "src/main.rs"
test = false
bench = false
doc = false

[lib]
name = "libhardqoi"
path = "src/lib.rs"
test = false
bench = false
doc = false
crate-type = ["lib"]

